version: '2'
services:
    mysql:
        image: mysql:5.5
        env_file: .env
        ports:
          - "3306:3306"
    php:
        build:
          dockerfile: ./Dockerfile
          context: ./
        volumes:
            - .:/var/www/html
        ports:
          - "80:80"